# Generated by Django 4.0.2 on 2022-03-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_service_delete_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='service_text',
        ),
    ]
