# Generated by Django 4.0.2 on 2022-03-16 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_rename_service_name_service_service_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employee_choice',
        ),
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
