# Generated by Django 4.0.2 on 2022-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_service_employee_choice_service_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
