# Generated by Django 4.0.2 on 2022-03-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
