# Generated by Django 4.0.2 on 2022-03-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_appointment_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='employee',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
