# Generated by Django 4.0.2 on 2022-03-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_appointment_appointment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_employee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='employee',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.service')),
            ],
        ),
    ]
