# Generated by Django 4.0.2 on 2022-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_appointment_appointment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_service',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_service',
            field=models.ManyToManyField(to='polls.Service'),
        ),
    ]
