# Generated by Django 4.0.2 on 2022-03-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_appointment_appointment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_employee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.employee'),
        ),
    ]
